Repository RAJIV81205/Weather-Blast, pull requests merged in 2025-08, with the labels that each got.

#118 UI improvement
  js/weather.js
Labels: GSSoC 25, Level 3 - Hard

#125 Added visual compass component to display wind direction
  index.html
  script.js
  style.css
Labels: GSSoC 25, Level 3 - Hard

#133 feat: added MUSIC WIDGET
  .vscode/launch.json
  css/music-widget.css
  index.html
  js/music-widget.js
  script.js
  style.css
Labels: enhancement, GSSoC 25, Level 3 - Hard

#140 Added Contributing.md
  CONTRIBUTING.md
Labels: GSSoC 25, Level 2 - Medium
